### ISSUE TITLE
git-feats: command not found

### ISSUE THREAD

**Issue by mykewould** [cknadler/git-feats#14]
Got this today trying to use git status. I think issues like this should be more "telling" or at least give more details to what's going on.

**Comment by cknadler** [comment]
It sounds like you have git aliased to git-feats without having the gem
installed.

Sent from my iPhone

On Dec 17, 2012, at 11:55 AM, Michael Wood notifications@github.com wrote:

Got this today trying to use git status. I think issues like this should be
more "telling" or at least give more details to what's going on.

—
Reply to this email directly or view it on
GitHubhttps://github.com/cknadler/git-feats/issues/14.

**Comment by mykewould** [comment]
Yeah and now thinking about it, we can't error that. Closed.
