### ISSUE TITLE
errors in 'git-feats --version'

### ISSUE THREAD

**Issue by dasmoose** [cknadler/git-feats#2]
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
git version 1.7.12

**Comment by cknadler** [comment]
We determined that this is specific to your system. Closing.
