### ISSUE TITLE
Switch comments to YARD format.

### ISSUE THREAD

**Issue by mykewould** [cknadler/git-feats#8]
I'm a big fan of YARD and its structure. I'm all for keeping the docs out of the repo, but I think a comment format should be used. Thoughts?

http://yardoc.org/

**Comment by cknadler** [comment]
I haven't used YARD at all before but it seems like a fantastic idea.

The gem needs a good hard refactoring. While I do that, I'll move the comments over to YARD.

:+1:

**Comment by mykewould** [comment]
I'll refactor as I complete tests. Leave Checker.check for me!

**Comment by cknadler** [comment]
No problem at all. I'll focus on the site. :smiley_cat:

**Comment by cknadler** [comment]
I'm gonna close this, still a work in progress it should happen naturally now as the code is refactored.
